sudo: false
osx_image: xcode611
language: objective-c
xcode_workspace: ShakedownSample.xcworkspace
xcode_scheme: ShakedownSample
xcode_sdk: iphonesimulator
cache:
- cocoapods
before_install:
- gem install cocoapods --prerelease